### ISSUE TITLE
Account is blocked in its first use

### ISSUE THREAD

**Issue by i3bdallah** [zzzace2000/us_scraper#1]
When I debugged the code, I noticed that this line is returning always `None `for me, hence it thinks my account blocked. However, in reality it is not.

`    time_table = soup.find("table", {"class": "for-layout"})`

time_table is always coming as None, why it is parsing the payment/confirmation page ?

Do you know why ?

**Comment by i3bdallah** [comment]
My mistake, issue fixed, didn't know that the application shouldn't be paid

**Comment by zzzace2000** [comment]
Oh yes! I forgot to mention that.
The point is not to use your main account to probe to avoid being blocked.

**Comment by i3bdallah** [comment]
@zzzace2000 Thanks, it is working fine, but did you notice a pattern ? like appointments become free at a certain time of day ? or is it random ?

**Comment by zzzace2000** [comment]
It's more random - I got mine like 10:57pm.
